### ISSUE TITLE
XS, XSMax, iPad Pro serial ID regex

### ISSUE THREAD

**Issue by albertJkt** [thebeet/idevicekit#5]
`let _checkSerial = (serial) => {
    return /^[a-z0-9]{40,40}$/.test(serial);
};`
This works only till A11 SoC. 

`let _checkSerial = (serial) => {
    return /^[a-z0-9]{40,40}$/ || /^[A-Z0-9]{8}-[A-Z0-9]{16}$/i.test(serial);
};` - this should fix the issue.

**Comment by thebeet** [comment]
[https://github.com/thebeet/idevicekit/commit/2ef115af16b33cff4468d3da03df4d19a236f507](url)

ISSUE fixed, Thank You :)
